# -*- coding: utf-8 -*-
"""BasicPrograms.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Sa8Fkj4TPfVmEV_TTIXMTC2NDg5ks0vH
"""

print('Hello World')

# This program adds two numbers

num1 = 2.5
num2 = 6.3

# Add two numbers
sum = num1 + num2

# Display the sum
print('The sum of {0} and {1} is {2}'.format(num1, num2, sum))

# Program to generate a random number between 0 and 9

# importing the random module
import random

print(random.randint(0,9))

# Python program to swap two variables

x = 5
y = 10

# To take inputs from the user
#x = input('Enter value of x: ')
#y = input('Enter value of y: ')

# create a temporary variable and swap the values
temp = x
x = y
y = temp

print('The value of x after swapping: {}'.format(x))
print('The value of y after swapping: {}'.format(y))